### ISSUE TITLE
cannot connect to server

### ISSUE THREAD

**Issue by nimahkh** [mirzaaghazadeh/iOS-Ad-hoc#2]
i do everything you do , and correct all of my information in plist , but again i have problem with it , i upload in diwi.com and everything is ok , but my plist is not working , it means , ipa az ok , and plist is not , how can i do this?

**Comment by mirzaaghazadeh** [comment]
This is not for diwi.com

For this you should sign the ipa file

**Comment by nimahkh** [comment]
my problem is that , i signed my ipa and everything is ok ,  now i want to create plist , but it does not working , problem is not ipa ,
it's for is plist , but i dont know how to resolve this problem , i used your plist , and nothing changed ,

**Comment by mirzaaghazadeh** [comment]
create plist with our sample!
just replace the string in https://github.com/mirzaaghazadeh/iOS-Ad-hoc/blob/master/x.plist

read the readme!
